### ISSUE TITLE
Eraser mode

### ISSUE THREAD

**Issue by napcat** [benrhodes/graffiti-as3-drawing-lib-touch#5]
Is the eraser mode a true eraser?

I'm asking this because it looks like it paint in white instead of really deleting the pixels.

Is this the correct way to setup a brush tool?

graffitiCanvas.brush = new HorizontalLineBrush(40, 0xFFFFFF, 1, BitmapCacheRenderMode.ERASE);

**Comment by benrhodes** [comment]
When you specify BitmapCacheRenderMode.ERASE you are setting a blend mode for the BitmapData draw command.  You can read up on exactly what it does here. http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/BlendMode.html

**Comment by napcat** [comment]
But BitmapCacheRenderMode.ERASE is all that I need to set?

I still doesn't have this working...

Is there any working example?

Thank you.
